APP_NAME := sensorcalculationTest
ARDUINO_LIBS := AUnit Adafruit_BusIO Adafruit-GFX-Library Adafruit_ILI9341 LiquidCrystal Adafruit_ADS1X15 EpoxyEeprom ambovis
include ../../../../EpoxyDuino/EpoxyDuino.mk
