name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt update
        # sudo apt install -y libcurl4-openssl-dev
        cd arduino/
        ls

        git clone --branch v1.5.0 https://github.com/bxparks/EpoxyDuino.git
        cd EpoxyDuino/cores/epoxy
        cp pins_arduino_avr.h pins_arduino.h

        sed -i.bkp '65i #ifndef LSBFIRST' SPI.h
        sed -i.bkp '66i #define LSBFIRST 0' SPI.h
        sed -i.bkp '67i #endif' SPI.h
        sed -i.bkp '68i #ifndef MSBFIRST' SPI.h
        sed -i.bkp '69i #define MSBFIRST 1' SPI.h
        sed -i.bkp '70i #endif' SPI.h
        
        sed -i.bkp '71i typedef enum _BitOrder {' SPI.h
        sed -i.bkp '72i SPI_BITORDER_MSBFIRST = MSBFIRST,' SPI.h
        sed -i.bkp '73i SPI_BITORDER_LSBFIRST = LSBFIRST,' SPI.h
        sed -i.bkp '74i } BitOrder;' SPI.h

        cd ../../..

        echo "clone Aunit"
        git clone --depth 1 https://github.com/bxparks/AUnit
        echo "clone liquid"
        git clone --depth 1 https://github.com/arduino-libraries/LiquidCrystal.git
        echo "clone adafruit"
        git clone --branch 2.3.0 https://github.com/adafruit/Adafruit_ADS1X15.git
        git clone --branch 1.7.3 https://github.com/adafruit/Adafruit_BusIO.git
        git clone --branch 1.10.9 https://github.com/adafruit/Adafruit-GFX-Library.git
        git clone --branch 1.5.6 https://github.com/adafruit/Adafruit_ILI9341.git
        
        cd Adafruit_BusIO/
        sed -i.bak -e '31,32d' Adafruit_SPIDevice.h
        cd ../

        ls
        cd ambovis/tests/unit-tests
        make > /dev/null
        ./dummyTest.out

    # - name: Verify examples
    #   run: |
    #     make -C examples
    #     make -C examples/MemoryBenchmark epoxy