name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt update > /dev/null 2>&1
        # sudo apt install -y libcurl4-openssl-dev
        cd arduino/

        echo "Clone EpoxyDuino..."
        git clone --branch v1.5.0 https://github.com/bxparks/EpoxyDuino.git > /dev/null 2>&1
        mv EpoxyDuino/EpoxyDuino.mk EpoxyDuino/EpoxyDuino.mk.bak
        # Use custom makefile
        echo "Customize EpoxyDuino for Ambovis"
        cp AmbovisEpoxyDuino.mk EpoxyDuino/EpoxyDuino.mk
        cd EpoxyDuino/cores/epoxy
        touch wiring_private.h
        cp pins_arduino_avr.h pins_arduino.h

        sed -i.bkp '65i #ifndef LSBFIRST' SPI.h
        sed -i.bkp '66i #define LSBFIRST 0' SPI.h
        sed -i.bkp '67i #endif' SPI.h
        sed -i.bkp '68i #ifndef MSBFIRST' SPI.h
        sed -i.bkp '69i #define MSBFIRST 1' SPI.h
        sed -i.bkp '70i #endif' SPI.h
        
        sed -i.bkp '71i typedef enum _BitOrder {' SPI.h
        sed -i.bkp '72i SPI_BITORDER_MSBFIRST = MSBFIRST,' SPI.h
        sed -i.bkp '73i SPI_BITORDER_LSBFIRST = LSBFIRST,' SPI.h
        sed -i.bkp '74i } BitOrder;' SPI.h

        cd ../../..

        echo "Clone Aunit"
        git clone --depth 1 https://github.com/bxparks/AUnit > /dev/null 2>&1
        echo "Clone liquid"
        git clone --branch 1.0.7 --depth 1 https://github.com/arduino-libraries/LiquidCrystal.git > /dev/null 2>&1
        echo "Clone adafruit set"
        git clone --branch 2.3.0 https://github.com/adafruit/Adafruit_ADS1X15.git > /dev/null 2>&1
        git clone --branch 1.7.3 https://github.com/adafruit/Adafruit_BusIO.git > /dev/null 2>&1
        git clone --branch 1.10.9 https://github.com/adafruit/Adafruit-GFX-Library.git > /dev/null 2>&1
        git clone --branch 1.5.6 https://github.com/adafruit/Adafruit_ILI9341.git > /dev/null 2>&1
        
        cd Adafruit_BusIO/
        sed -i.bak -e '31,32d' Adafruit_SPIDevice.h
        cd ../

        cd ambovis/tests/unit-tests/
        make runtests
        