name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt update
        # sudo apt install -y libcurl4-openssl-dev
        cd arduino/
        ls
        echo "clone Aunit"
        git clone --depth 1 https://github.com/bxparks/AUnit
        echo "clone liquid"
        git clone --depth 1 https://github.com/arduino-libraries/LiquidCrystal.git
        ls
        cd ambovis/tests/unit-tests
        # make > /dev/null
        # ./dummyTest.out

    # - name: Verify examples
    #   run: |
    #     make -C examples
    #     make -C examples/MemoryBenchmark epoxy